// <auto-generated />
using System;
using System.Collections.Generic;
using Garden.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Garden.Infrastructure.Migrations
{
    [DbContext(typeof(GardenDbContext))]
    [Migration("20260713033423_AddSettlementCarryingCapacity")]
    partial class AddSettlementCarryingCapacity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Garden.World.Entities.Citizen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BirthTick")
                        .HasColumnType("bigint");

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ContributionScore")
                        .HasColumnType("double precision");

                    b.Property<string>("CurrentActivity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentGoal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("DeathTick")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("HomeSettlementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("KnownEventIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ReligionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReligionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Reputation")
                        .HasColumnType("double precision");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("TileX")
                        .HasColumnType("integer");

                    b.Property<int>("TileY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("Garden.World.Entities.CulturalTrait", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EstablishedTick")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SettlementId")
                        .HasColumnType("uuid");

                    b.Property<double>("Strength")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.ToTable("CulturalTrait");
                });

            modelBuilder.Entity("Garden.World.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthoritySource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CarryingCapacity")
                        .HasColumnType("double precision");

                    b.Property<long>("FoundedTick")
                        .HasColumnType("bigint");

                    b.Property<string>("GovernmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("KingdomId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastGovernmentChangeTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uuid");

                    b.Property<string>("LeaderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Legitimacy")
                        .HasColumnType("double precision");

                    b.Property<List<Guid>>("MemberIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReligionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReligionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TechnologyProgress")
                        .HasColumnType("double precision");

                    b.Property<double>("TerritorialInfluence")
                        .HasColumnType("double precision");

                    b.Property<int>("TerritoryRadius")
                        .HasColumnType("integer");

                    b.Property<int>("TileX")
                        .HasColumnType("integer");

                    b.Property<int>("TileY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Settlements");
                });

            modelBuilder.Entity("Garden.World.Entities.Citizen", b =>
                {
                    b.OwnsOne("Garden.World.Entities.CitizenAttributes", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Dexterity")
                                .HasColumnType("double precision");

                            b1.Property<double>("Endurance")
                                .HasColumnType("double precision");

                            b1.Property<double>("Intelligence")
                                .HasColumnType("double precision");

                            b1.Property<double>("Perception")
                                .HasColumnType("double precision");

                            b1.Property<double>("Strength")
                                .HasColumnType("double precision");

                            b1.HasKey("CitizenId");

                            b1.ToTable("Citizens");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.OwnsMany("Garden.World.Entities.CitizenMemory", "Memories", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<long>("Tick")
                                .HasColumnType("bigint");

                            b1.HasKey("CitizenId", "Id");

                            b1.ToTable("CitizenMemory");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.OwnsOne("Garden.World.Entities.CitizenNeeds", "Needs", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Energy")
                                .HasColumnType("double precision");

                            b1.Property<double>("Health")
                                .HasColumnType("double precision");

                            b1.Property<double>("Hunger")
                                .HasColumnType("double precision");

                            b1.Property<double>("Thirst")
                                .HasColumnType("double precision");

                            b1.Property<double>("Warmth")
                                .HasColumnType("double precision");

                            b1.HasKey("CitizenId");

                            b1.ToTable("Citizens");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.OwnsOne("Garden.World.Entities.EmotionalState", "Emotions", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Curiosity")
                                .HasColumnType("double precision");

                            b1.Property<double>("Fear")
                                .HasColumnType("double precision");

                            b1.Property<double>("Joy")
                                .HasColumnType("double precision");

                            b1.Property<double>("Loneliness")
                                .HasColumnType("double precision");

                            b1.Property<double>("Sadness")
                                .HasColumnType("double precision");

                            b1.Property<double>("Trust")
                                .HasColumnType("double precision");

                            b1.HasKey("CitizenId");

                            b1.ToTable("Citizens");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.OwnsOne("Garden.World.Entities.PersonalityTraits", "Personality", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Aggression")
                                .HasColumnType("double precision");

                            b1.Property<double>("Compassion")
                                .HasColumnType("double precision");

                            b1.Property<double>("Curiosity")
                                .HasColumnType("double precision");

                            b1.Property<double>("Diligence")
                                .HasColumnType("double precision");

                            b1.Property<double>("Introversion")
                                .HasColumnType("double precision");

                            b1.Property<double>("Patience")
                                .HasColumnType("double precision");

                            b1.HasKey("CitizenId");

                            b1.ToTable("Citizens");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Emotions")
                        .IsRequired();

                    b.Navigation("Memories");

                    b.Navigation("Needs")
                        .IsRequired();

                    b.Navigation("Personality")
                        .IsRequired();
                });

            modelBuilder.Entity("Garden.World.Entities.CulturalTrait", b =>
                {
                    b.HasOne("Garden.World.Entities.Settlement", null)
                        .WithMany("CulturalTraits")
                        .HasForeignKey("SettlementId");
                });

            modelBuilder.Entity("Garden.World.Entities.Settlement", b =>
                {
                    b.OwnsMany("Garden.World.Entities.Building", "Buildings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("AssignedWorkerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BuildProgress")
                                .HasColumnType("integer");

                            b1.Property<int>("BuildTimeRequired")
                                .HasColumnType("integer");

                            b1.Property<string>("BuildingType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.Property<int>("TileX")
                                .HasColumnType("integer");

                            b1.Property<int>("TileY")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("SettlementId");

                            b1.ToTable("Building");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");

                            b1.OwnsOne("Garden.World.Entities.Inventory", "Storage", b2 =>
                                {
                                    b2.Property<Guid>("BuildingId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("MaxCapacity")
                                        .HasColumnType("double precision");

                                    b2.HasKey("BuildingId");

                                    b2.ToTable("Building");

                                    b2.WithOwner()
                                        .HasForeignKey("BuildingId");

                                    b2.OwnsMany("Garden.World.Entities.ItemStack", "Items", b3 =>
                                        {
                                            b3.Property<Guid>("InventoryBuildingId")
                                                .HasColumnType("uuid");

                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("ItemType")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<double>("Quantity")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("StackLimit")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Weight")
                                                .HasColumnType("double precision");

                                            b3.HasKey("InventoryBuildingId", "Id");

                                            b3.ToTable("Building_Items");

                                            b3.WithOwner()
                                                .HasForeignKey("InventoryBuildingId");
                                        });

                                    b2.Navigation("Items");
                                });

                            b1.Navigation("Storage")
                                .IsRequired();
                        });

                    b.OwnsOne("Garden.World.Entities.Inventory", "Storage", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.Property<double>("MaxCapacity")
                                .HasColumnType("double precision");

                            b1.HasKey("SettlementId");

                            b1.ToTable("Settlements");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");

                            b1.OwnsMany("Garden.World.Entities.ItemStack", "Items", b2 =>
                                {
                                    b2.Property<Guid>("InventorySettlementId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<double>("Quantity")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("StackLimit")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Weight")
                                        .HasColumnType("double precision");

                                    b2.HasKey("InventorySettlementId", "Id");

                                    b2.ToTable("Settlements_Items");

                                    b2.WithOwner()
                                        .HasForeignKey("InventorySettlementId");
                                });

                            b1.Navigation("Items");
                        });

                    b.Navigation("Buildings");

                    b.Navigation("Storage")
                        .IsRequired();
                });

            modelBuilder.Entity("Garden.World.Entities.Settlement", b =>
                {
                    b.Navigation("CulturalTraits");
                });
#pragma warning restore 612, 618
        }
    }
}
